version: "3.8"
services:
  consul1:
    container_name: consul1
    image: consul:1.8.3
    deploy:
      mode: replicated
      replicas: 1
    command:
      - "agent"
      - "-server"
      - "-bootstrap-expect=3"
      - "-ui"
      - "-data-dir=/opt/data"
    networks:
      consul:
        ipv4_address: 172.26.0.2
    volumes:
      - "$PWD/consul/data/1:/opt/data"
  consul2:
    container_name: consul2
    image: consul:1.8.3
    deploy:
      mode: replicated
      replicas: 1
    command:
      - "agent"
      - "-server"
      - "-bootstrap-expect=3"
      - "-ui"
      - "-data-dir=/opt/data"
    networks:
      consul:
        ipv4_address: 172.26.0.3
    volumes:
      - "$PWD/consul/data/2:/opt/data"
  consul3:
    container_name: consul3
    image: consul:1.8.3
    deploy:
      mode: replicated
      replicas: 1
    command:
      - "agent"
      - "-server"
      - "-bootstrap-expect=3"
      - "-ui"
      - "-client=0.0.0.0"
      - "-data-dir=/opt/data"
    networks:
      consul:
        ipv4_address: 172.26.0.4
    volumes:
      - "$PWD/consul/data/3:/opt/data"
  
  lb:
    container_name: lb
    build:
      dockerfile: dockerfile
      context: ./nginx
    links:
      - consul1
      - consul2
      - consul3
    ports:
      - 8500:8500
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      consul: {}
networks:
  consul:
    name: consul
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
    